---
abstract: 'Teng plugin for Joined query'
author:
  - 'Masayuki Matsuki <y.songmu@gmail.com>'
build_requires:
  Test::More: 0.98
  parent: 0
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Teng-Plugin-SearchJoined
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Teng::Plugin::SearchJoined:
    file: lib/Teng/Plugin/SearchJoined.pm
    version: 0.02
  Teng::Plugin::SearchJoined::Iterator:
    file: lib/Teng/Plugin/SearchJoined/Iterator.pm
    version: 0
requires:
  Class::Accessor::Lite: 0
  SQL::Maker: 0
  SQL::Maker::Plugin::JoinSelect: 0
  Teng: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/Songmu/p5-Teng-Plugin-SearchJoined/issues
  homepage: https://github.com/Songmu/p5-Teng-Plugin-SearchJoined
  repository: git://github.com/Songmu/p5-Teng-Plugin-SearchJoined.git
version: 0.02
